#!/bin/sh
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample, or uncomment the next line and
# rename the file to "post-receive".
#
# AZ:
# Deploy app
#

SYMLINK=/tmp/NewApp

TMP_DIR=`mktemp -d`
git archive HEAD | tar x -C $TMP_DIR
cd $TMP_DIR
cd backend/app
find -type f -name '.gitignore' -exec rm {} \;
npm install --production
mv $TMP_DIR/backend/node_modules/ $TMP_DIR/backend/app/

# now copy the app as is into the app directory
ts=`date '+%Y%m%d-%H%M%S'`
DEPLOY_DIR=/tmp/$ts
mkdir $DEPLOY_DIR
cp -r . $DEPLOY_DIR

# add config file
# ...@TODO

rm $SYMLINK
ln -s $DEPLOY_DIR $SYMLINK

#rm -fr $TMP_DIR
exit 0
